# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/luizhenrique/Desktop/gerencialab

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/luizhenrique/Desktop/gerencialab

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/luizhenrique/Desktop/gerencialab/CMakeFiles /Users/luizhenrique/Desktop/gerencialab//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/luizhenrique/Desktop/gerencialab/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GerenciaLab

# Build rule for target.
GerenciaLab: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GerenciaLab
.PHONY : GerenciaLab

# fast build rule for target.
GerenciaLab/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GerenciaLab.dir/build.make CMakeFiles/GerenciaLab.dir/build
.PHONY : GerenciaLab/fast

#=============================================================================
# Target rules for targets named GerenciaLab_autogen_timestamp_deps

# Build rule for target.
GerenciaLab_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GerenciaLab_autogen_timestamp_deps
.PHONY : GerenciaLab_autogen_timestamp_deps

# fast build rule for target.
GerenciaLab_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GerenciaLab_autogen_timestamp_deps.dir/build.make CMakeFiles/GerenciaLab_autogen_timestamp_deps.dir/build
.PHONY : GerenciaLab_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named GerenciaLab_autogen

# Build rule for target.
GerenciaLab_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GerenciaLab_autogen
.PHONY : GerenciaLab_autogen

# fast build rule for target.
GerenciaLab_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GerenciaLab_autogen.dir/build.make CMakeFiles/GerenciaLab_autogen.dir/build
.PHONY : GerenciaLab_autogen/fast

#=============================================================================
# Target rules for targets named common

# Build rule for target.
common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 common
.PHONY : common

# fast build rule for target.
common/fast:
	$(MAKE) $(MAKESILENT) -f src/common/CMakeFiles/common.dir/build.make src/common/CMakeFiles/common.dir/build
.PHONY : common/fast

#=============================================================================
# Target rules for targets named common_autogen_timestamp_deps

# Build rule for target.
common_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 common_autogen_timestamp_deps
.PHONY : common_autogen_timestamp_deps

# fast build rule for target.
common_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f src/common/CMakeFiles/common_autogen_timestamp_deps.dir/build.make src/common/CMakeFiles/common_autogen_timestamp_deps.dir/build
.PHONY : common_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named common_autogen

# Build rule for target.
common_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 common_autogen
.PHONY : common_autogen

# fast build rule for target.
common_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/common/CMakeFiles/common_autogen.dir/build.make src/common/CMakeFiles/common_autogen.dir/build
.PHONY : common_autogen/fast

#=============================================================================
# Target rules for targets named lab-fila

# Build rule for target.
lab-fila: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lab-fila
.PHONY : lab-fila

# fast build rule for target.
lab-fila/fast:
	$(MAKE) $(MAKESILENT) -f src/lab-fila/CMakeFiles/lab-fila.dir/build.make src/lab-fila/CMakeFiles/lab-fila.dir/build
.PHONY : lab-fila/fast

#=============================================================================
# Target rules for targets named lab-fila_autogen_timestamp_deps

# Build rule for target.
lab-fila_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lab-fila_autogen_timestamp_deps
.PHONY : lab-fila_autogen_timestamp_deps

# fast build rule for target.
lab-fila_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f src/lab-fila/CMakeFiles/lab-fila_autogen_timestamp_deps.dir/build.make src/lab-fila/CMakeFiles/lab-fila_autogen_timestamp_deps.dir/build
.PHONY : lab-fila_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named lab-fila_autogen

# Build rule for target.
lab-fila_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lab-fila_autogen
.PHONY : lab-fila_autogen

# fast build rule for target.
lab-fila_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/lab-fila/CMakeFiles/lab-fila_autogen.dir/build.make src/lab-fila/CMakeFiles/lab-fila_autogen.dir/build
.PHONY : lab-fila_autogen/fast

GerenciaLab_autogen/mocs_compilation.o: GerenciaLab_autogen/mocs_compilation.cpp.o
.PHONY : GerenciaLab_autogen/mocs_compilation.o

# target to build an object file
GerenciaLab_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GerenciaLab.dir/build.make CMakeFiles/GerenciaLab.dir/GerenciaLab_autogen/mocs_compilation.cpp.o
.PHONY : GerenciaLab_autogen/mocs_compilation.cpp.o

GerenciaLab_autogen/mocs_compilation.i: GerenciaLab_autogen/mocs_compilation.cpp.i
.PHONY : GerenciaLab_autogen/mocs_compilation.i

# target to preprocess a source file
GerenciaLab_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GerenciaLab.dir/build.make CMakeFiles/GerenciaLab.dir/GerenciaLab_autogen/mocs_compilation.cpp.i
.PHONY : GerenciaLab_autogen/mocs_compilation.cpp.i

GerenciaLab_autogen/mocs_compilation.s: GerenciaLab_autogen/mocs_compilation.cpp.s
.PHONY : GerenciaLab_autogen/mocs_compilation.s

# target to generate assembly for a file
GerenciaLab_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GerenciaLab.dir/build.make CMakeFiles/GerenciaLab.dir/GerenciaLab_autogen/mocs_compilation.cpp.s
.PHONY : GerenciaLab_autogen/mocs_compilation.cpp.s

src/main/main.o: src/main/main.cpp.o
.PHONY : src/main/main.o

# target to build an object file
src/main/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GerenciaLab.dir/build.make CMakeFiles/GerenciaLab.dir/src/main/main.cpp.o
.PHONY : src/main/main.cpp.o

src/main/main.i: src/main/main.cpp.i
.PHONY : src/main/main.i

# target to preprocess a source file
src/main/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GerenciaLab.dir/build.make CMakeFiles/GerenciaLab.dir/src/main/main.cpp.i
.PHONY : src/main/main.cpp.i

src/main/main.s: src/main/main.cpp.s
.PHONY : src/main/main.s

# target to generate assembly for a file
src/main/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GerenciaLab.dir/build.make CMakeFiles/GerenciaLab.dir/src/main/main.cpp.s
.PHONY : src/main/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GerenciaLab_autogen"
	@echo "... GerenciaLab_autogen_timestamp_deps"
	@echo "... common_autogen"
	@echo "... common_autogen_timestamp_deps"
	@echo "... lab-fila_autogen"
	@echo "... lab-fila_autogen_timestamp_deps"
	@echo "... GerenciaLab"
	@echo "... common"
	@echo "... lab-fila"
	@echo "... GerenciaLab_autogen/mocs_compilation.o"
	@echo "... GerenciaLab_autogen/mocs_compilation.i"
	@echo "... GerenciaLab_autogen/mocs_compilation.s"
	@echo "... src/main/main.o"
	@echo "... src/main/main.i"
	@echo "... src/main/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

